Dataset creation and and .csv link fix (#1)
Fix for:
~~~python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-ef98bcea6c26> in <module>()
      1 dataset = client.dataset(DEST_DATASET)
----> 2 dataset.create()

AttributeError: 'DatasetReference' object has no attribute 'create'
~~~
And:
~~~python
FileNotFoundError: File b'./data/20k_G06F_publication_numbers.csv' does not exist
~~~